

import React from "react"
import Layout from "../components/layout"
import { css } from '@emotion/react'
import { Link } from "gatsby"
import Helmet from "react-helmet"

import vilhelm_hammershoi_3 from "../img/hammershoi4.jpg"
import vilhelm_hammershoi_4 from "../img/landscape.jpg"

const faqPage = ({ data }) => (
  <Layout>
    <Helmet>
      <title>FAQ for 'Holmschooling' a Computer Science Education for Free</title>
      <meta name="description" content="Frequently asked questions about 'Holmschooling' your way to becoming a programmer for free! What is OER or OCW? Find out!"/>
    </Helmet>
    <div className={`bigimages`} css={css`margin-top: 70px;@media screen and (min-width: 800px) { margin-top: 48px;}`}>
      <img src={vilhelm_hammershoi_3} width="100%" alt="Painting 'The Music Room' by Vilhelm Hammershøi, 1907"/>
    </div>
    <div css={css`
      margin: 0 auto;
      max-width: 800px;
      padding: 0 10px;
    `}>
        <h1>FAQ for 'Holmschooling' a Free Computer Science Education</h1>
        <h3>"Isn't OER is written by second rate authors?"</h3>
        <p>How rude! And a firm no. Most "first rate" textbook authors aren't actually any more famous or successful, but just notorious due to the high expense of their textbook! Think of it this way: If you are successful enough in your career as a programmer that you can afford to distribute your blood sweat and tears for free, you're probably a successful programmer with money to spare. I'd rather learn from successful programmers than unsuccessful programmer, wouldn't you? And many OER authors receive their payment through grants or stipends in advanced of open sourcing their book, so while still philanthropic, people do get paid. Open source is not a mark of inferiority in code, and neither is it in books. It's just a different paradigm: open collaboration towards a free and reproducible product instead of a centralized, proprietary product. The quality is the same, just the copyright is different.</p>
        <h3>"But if I don't get the $&#123;top_rated_$200_textbook&#125; I'll wind up a Terrible Programmer That Won't Change the World!"</h3>
        <p>That's a dire thought. To think of how many people have been kept back from changing the world because they didn't buy the most expensive textbook on the market. And the author probably only get a $5 commission on each sale too. You're saying they could have changed the world thousands of times over for a mere $5 commission? I'm not sure those authors are heroes, then, but scoundrels! To prevent the world from changing over $5! Harumph.</p>
        <p>If you really feel like not reading a particular textbook would prevent you from changing the world, but you can't afford it, I suggest you just get the book free through Interlibrary Loans at your local public library along with studying the equivalent OER too. You can take photographs of your books with your cell phone nowadays if you're concerned about the due date approaching too fast... just saying. If something really changed the world for the better, chances are it would be free. And, my point is, it does and is: That's why OER is free.</p>
        <h3>"OER is like buying a fake Louis Vuitton! Everyone knows you're a ersatz fraud!"</h3>
        <p>If no one can tell a difference between a Turing Award-winning scientist who went to a Tier 1 school and a Turing Award-winning scientist who Holm Schooled, is there really any? Aim high, kids.</p>
        <h3>"I'll never win a Turing Award if I don't go to MIT!"</h3>
        <p>I believe if you're smart enough to get into MIT, you're smart enough to Holm School and still win that Turing Award. And, rather than spending that million dollar reward paying off your MIT student loan, you can retire to focus on winning more awards through your scholarship.</p>
        <h3>"You sound like a bum! Only the feebleminded don't go to college!"</h3>
        <p>I fully support going to college, but just that you do it after you secure your first programming job that pays tuition reimbursement benefits. And then not pay a cent through going through cheap online degrees like UoPeople and GATech OMSCS for your benefit. Holm Schoolers are the opposite of bums. In fact, since they lack external stimuli like grades and degrees and are driven only by inner drive, they are perhaps the most motivated computer scientists out there. Part of what makes it seem "bumful" is that most people don't realize the copious amounts of open educational resources out there in this day and age. They think Holm Schoolers simply aren't studying or reading. But within the decade there will be a Spotify for Books. The entire concept of going to the library to study will be replaced with going to your study to library. You aren't missing the library by holmschooling, in fact you're just accepting the fact that books are now delivered directly to your quarter-inch thick iPad rather than in paper form at your university library. Think how much all that storage for paper books costs to a university! Good riddance to the paper trail of university libraries. Perhaps now that all books are digital, they can clear out the miles of stacks and put in some lovely soft reading chairs and study kiosks. And increase enrollment for all that fresh study space, so they can lower tuition costs. Or you can just study at the kiosk and comfy reading chairs in your own home and not worry about tuition at all. What's the difference between reading at your university library and reading at your home? Especially if the money saved by not paying tuition funds your social life with friends in your free time. Seems like a win-win.</p>
        <h3>"If I study computer science for 4 years but don't have a degree, I won't have a good career"</h3>
        <p>That's the great thing about computer science. It's actually kind of a meritocracy. Since prestige doesn't matter to anyone not interested in academia, you can completely ignore prestige, save a bucket load of money, and still find employment as a computer scientist. If you study computer science for four years straight and contribute to open source, you'll probably be able to find a junior development job that will start your career. You obviously won't find any teachers who say that, but your teachers aren't computer scientists. You'll find plenty of computer scientists who say that. University is a luxury for the rich, its cost is not justifiable in this day and age of open source internets.</p>
        <h3>"Only idiots haven't read the Dragon Book. And computer science educators who don't promote reading the Dragon Book are idiots too!"</h3>
        <p>St. George all mighty, you're a nerd! Take a breather for a minute. While esoteric computer science can and does open doors to those lucky enough not to be facing immediate economic pressure, to think that only one book can do so is a bit... fundamentalist. Free OER compilers books will do just fine, thank you very much, and if you're studying computer science you're probably not an idiot anyway, so don't let the textbook fashionistas critique the hipness of your OER. If you really need to read a book, get it through interlibrary loans for free. I doubt there's much of a line for the Dragon Book!  The general masses have yet to get bitten by the compilers bug. Holm School is a catalog of OER to ensure it's 100% free, so I don't include the Dragon Book (among other superstar textbooks). Read it if you can get it for free.</p>
        <h3>"Can I make friends if I don't go to college?"</h3>
        <p>Yes, in fact it's easier since you'll be getting friends in your hometown at age 18. And since there's no reason to have to move to an expensive coastal city to pay for your egregious student loans, you can stay in your hometown and keep seeing your friends. You won't go to a private university in a different city for four years, leaving all your high school friends behind, only to make a new set of friends in four years, and then only to have to leave them in four years when you move to Silicon Valley. Bloom where you're planted. In the day and age where you can entertain yourself for free through the internet and your public library's digital lendings, what's the need to move to a big city for friends and hijinks? And since you'll have taken my advice to become a vegan straightedger, you won't have pickled your (still developing) brain with weekly alcohol binging at age 18 through the intellectually detrimental social scene that seemingly is mandatory at colleges. Keg stand friends aren't real friends, no matter what the movies say. Make some damn friends in your hometown, and don't think college is the solution to a problem you probably don't have anyway.</p>
        <h3>"What can I do with the $200 I save not buying a textbook?"</h3>
        <p>Put it in a Vanguard Roth IRA and buy VTSAX. Or buy a used bike on craigslist and a new helmet and lights at the bikeshop and live it up, biking everywhere you go around town. That's a better use of your $200 than the hours work you would have to do at your minimum wage work study job just to pay for a $200 textbook, multiplied by four classes per semester, multiplied by two semesters a year. Hello, this is computer science, not a luxury handbag. Paying more for a textbook than a good used bike just shows how scammish college has become. A bike has more utility than a book, buy a bike and read OER.</p>
        <h3>"Who the hell do you think you are? You can't criticize college, think about all the good things it's done for America!"</h3>
        <p>My name is "Nobody", Polyphemus.</p>
        <h3>"Can I trust you?"</h3>
        <p>As much as you can trust someone who started programming in sixth grade and knows quite a lot about open source computer culture, without even having a B.S. in CS. I was an art history major. Never abandon being a critical thinker. Question everything I type.</p>
        <p>However, Holm School is based on the <a href={`https://www.acm.org/binaries/content/assets/education/cs2013_web_final.pdf`}>ACM Computer Science Curriculum Guideslines (2013)</a>. Holm School's goals is not to just teach you to program, but to actually get the same computer science education that you would receive at a university. In that way, I've taken no short cuts on the standardized curriculum of classes. Everything in ACM's recommendations are present here at Holm School, so you can trust the curriculum and any shortcomings you perceive can be corrected by consulting the <a href={`https://github.com/EbookFoundation/free-programming-books`}>EbookFoundation/free-programming-books</a> repository to choose the necessary free texts yourself. Feel free to file a Github issue on <a href={`https://holmschool.github.io`}>pjenguenworks/HolmSchool</a> as well with criticisms of the curriculum and suggestions. My goal is not to filter the ACM curriculum into an abridged "best hits" of a CS curriculum, I instead want the Holm School course to mirror a full four-year CS curriculum using the ACM's recommendations as a guideline. The ACM guidelines were created based on what industry wants their junior developers to know when they begin work in career jobs. To ignore their recommendations would be shortsighted for anyone hoping to be a successful computer scientist. I recommend anyone new to being a programmer to read the ACM curriculum guidelines to get acquainted with what's expected of junior developers.</p>
        <h3>"Open Source Culture never paid the bills"</h3>
        <p>Who needs to pay the bills when everything is free? <a href={`https://www.youtube.com/watch?v=FBaVwwuErmU`}>Look Around You.</a> Microsoft is now an open source company. Microsoft. Let that sink in.</p>
        <h3>"Why so many languages throughout the curriculum? Why not one core language for the first few years and focus exclusively on that?"</h3>
        <p>The thing about learning languages that isn't apparent to new programmers is that, once you learn the fundamentals in one language, you can easily learn a new programming language in as little time as a month. The main difference is just a matter of syntax, and the more familiar you are with the fundamentals of computer science, the easier it is to learn and memorize those syntaxes. Though my particular computer science classes were almost exclusively Java, it was the summer break after my first semester that I taught myself C through CS50. Learning C was easy, and it augmented my Java skills come the next semester when I was back programming Java in class. The winter break following my second semester, I deep dove into Python and JavaScript on Treehouse. That too was easy and I was very successful learning Python and JavaScript despite being a one year old programmer. That is because I worked very hard my first semester and packed a year of learning in that first semester. It was a good thing that I departed from just learning one programming language. It was doable, and come time to apply for junior dev positions, I knew the languages they were developing in well enough that I got hired. If I had just stuck with Java, I would not have gotten hired or even applied to those jobs. So I promote being polylinguistic as a computer scientist, even a new one. Just learn the fundamentals in one language, then take what you've learned and apply those fundamentals while studying the syntax of a new language. It's actually easier than you might fear.</p>
        <h3>"I'll never get a job without a degree"</h3>
        <p>What's the bigger risk? Not maxing out your Roth IRA by contributing $6000 a year from age 18-22, striking a million dollars from your retirement, or not being able to find a junior dev position after study CS for four years? Seems like the latter is less risky. And what if you do get a junior dev job that pays as a benefit tuition reimbursement? Considering you'll know how to program after four years of studying, you'll breeze through your online classes even while working full time and earn your degree at zero cost. Keep maxing out your 401k and IRA from age 22+ by living frugally and damn, son, looks like you're financially independent at 35. You'll have a B.S. in CS from UoPeople and a M.S. in CS from GATech, and retired at 35. Perhaps you can start a killer open source repo. Or write OER textbooks. Or keep programming just for the fun of it. Sorry for my advice, you really should have stayed in school and worked till you are 65 to pay off your debt you couldn't afford when you signed up for nonbankruptable government loans at age 18. My bad.</p>
        <h3>"Will I be a success without a college degree?"</h3>
        <p>So much in life is about paying for our own perceive success amongst peers. Things like fashion, cars, houses, and colleges all are used as a surrogate for success. Unfortunately, colleges are today more of a fashion item whereas your "success" in life is read through the perceived cost of your fashion item. That's a stupid road to partake, and I hope you can study critical thinking enough to see that holmschooling with OER is a rational choice given the exploding cost of college. The solution to the problem of college cost is not to ignore the cornucopia of OER. OER is the solution to the problem of college cost. UoPeople is the solution to college cost. Treehouse is the solution to the problem of college cost. So is the public library. College isn't the solution to the problem of college cost. "Pay more for college and you'll earn more in your first job to help pay for your enormous student loans!" Yeah, thanks, I heard that line from my local pyramid scheme saleswoman... er... "influencer." The solution to the student loan crisis is not more college.</p>
        <h3>"What if I get a scholarship?"</h3>
        <p>Go. 8% inflation per year on "free" is still zero. Anyone can tolerate 8% inflation when the premium is zero dollars. Go, have fun, congrats on your hard work in high school. You should be an open source computer scientist.</p>
        <h3>"How do I open source my content?"</h3>
        <p><a href={`https://opensource.guide/legal/`}>Open Source Your School.</a> Open source everything. Digitize the analog. A whole lot of college professors will tell you that's bad. That open source lacks soul. Paying for college, man, no matter the price, man, is soul. But I think they're just lazy.</p>
        <h3>"I wanted to be a professor, though"</h3>
        <p>You probably wanted to be a professor because you're a generous person. The nice thing about the current state of affair, with the internet and open source and such, is that generous people can now affect millions of people instead of just 20 students per class. University was the killer app for smart and generous people back in the day, now open source licenses are the killer app for smart and generous people. By using and creating OER instead of going through the costly rigmarole of the academic hierarchy, generous people can create content that will allow people who never have the opportunity to learn computer science to do so.</p>
        <h3>"Companies won't even look at a resume without a college degree"</h3>
        <p>Truth told, let them! And you know what? Any company that would reject a resume just for not having a college degree is probably a place you don't want to work for. They probably don't even understand open source. They don't even know that computer scientists in particular have millions of hours of free undergraduate education on the internet. My guess is, they're enterprise and corporate. And, if they won't even look at your resume, find another job that does hire you. And then use tuition reimbursement to get a UoPeople degree. Then get an OMSCS degree. And then apply for that company with a master's degree. You don't have to have an elite job starting right at 22, you can just find a junior dev job that still offers tuition reimbursement, get your schooling done (for free) from ages 22-24 at UoPeople and OMSCS, then start applying to jobs that require a resume.</p>
        <p>Most employers who are hip to current technology are aware that you don't need a degree anymore for CS. Unfortunately, many HR departments are not. But if the computer science managers on the team don't tell HR to consider applications with good Github contributions and a good portfolio, rather than a degree, then they are an employer that isn't considerate of open source and modern engineering. If they don't even take the effort to teach HR, then do you expect them to teach YOU anything as an employee? They probably won't, and so you probably shouldn't even care that they wouldn't hire you and go work somewhere else. You don't want to work for a lazy employer. If you Holm School CS hardcore for four years, you will probably get a job since there is such a high demand. If you're concerned, you can spend $1000 a year and get a UoPeople B.S. in CS. Otherwise, put off official school until you earn tuition reimbursement.</p>
        <h3>"No one will hire anyone with a UoPeople degree"</h3>
        <p>That's why you also complete your Treehouse curriculum at the same time you're doing UoPeople. If you complete UoPeople and 100% complete every class at Treehouse, you'll be quite capable of making open source coding projects and be able to build your resume on Github. Github is like a resume these days, and it's a great way to benefit from direct practicing of coding by making open source repositories. With UoPeople complete, Treehouse complete, and an extensive Github resume, you'll be more than qualified for a junior development job that'll pay tuition reimbursement on your OMSCS degree as well as enable you to max out a 401K and IRA and invest in S&P500 or total stock market index. And if you do that in your twenties, <Link to={`/the-f-you-degree`}>with an educational debt you paid off working 3 hours a week minimum wage</Link>, you'll make out like a bandit.</p>
        <p>Like I said in my <Link to={`/guide`}>Guide to Being a Not-Rich Computer Scientist</Link>, if an employer won't hire you just because you have a "social justice" computer science degree, it's probably not an employer you want to work for. Their loss, not yours. There are so many programming jobs out there I don't think you need to worry. Having a UoPeople degree is awesome. You shouldn't feel bad for being frugal and strategic in regards to postsecondary educational costs. Once you get a junior dev job, degrees don't even matter and experience is king. If you can't get a job with UoPeople, you can always get an OMSCS degree for just $7000 and two years more.</p>
        <h3>"What is the future of Holm School?"</h3>
        <p>People might think Holm School is about OER, but it's real purpose is to promote frugality (yes, even in regards to school tuition, as taboo as criticizing spending money on education is). Kids just don't realize that debt at a young age is monumentally deterimental. And, in my opinion, ruins lives. I want to empower kids who are interested in computers to combine their drive for learning to program with the sort of benefits that come from being frugal and wise about tax-advantaged investment vehicles and index funds even at an early age. The time to learn about investment and a 401k and IRA isn't at your first job, it's before you sign the dotted line for huge nonbankruptable student loans. Colleges and professors and staff benefit, ironically, when students are unwise. I want to break from that cycle of violence and emphasize the true cost of college. A lot of people will complain that OER and Open Education don't suggest a rejection of higher education, but as long as higher education is not free that will be my position. No philosophical reward, such as a degree, is worth debt at a young age. As long as college is not free, I will use OER and Open Education to advocate unschooling, knowing full well that most OER creators and even unschooling advocates are college professors. The irony does not disturb me, to me it is just cold hard math. As long as Treehouse, Lynda, PluralSight, and others continue comparable educational resources for just a couple hundreds of dollars a year, especially when combined with resources like your public library or OER/OCW, the math indicates towards unschooling. Maybe someday college will be free, all degrees will be Z Degrees, etc. But a bubble is a bubble and I doubt it. Given the ease of a solution: OER/OCW, I think a solution has been found.</p>
        <div className="bigimages">
          <img src={vilhelm_hammershoi_4} alt="Painting 'Landscape, Kongevejen near Gentofte' by Vilhelm Hammershøi, 1892" width="100%" className={css`margin-bottom: 0px;`} />
        </div>
    </div>
</Layout>
)


export default faqPage;